app/Http/routes.php
<?php
  
use Illuminate\Support\Facades\Route;
  
use App\Http\Controllers\GoogleController;
  
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
  
Route::get('auth/google', [GoogleController::class, 'redirectToGoogle']);
Route::get('auth/google/callback', [GoogleController::class, 'handleGoogleCallback']);

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GoogleController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('input');
});

Route::get('auth/google', [GoogleController::class, 'redirectToGoogle']);
Route::get('auth/google/callback', [GoogleController::class, 'handleGoogleCallback']);

Route::middleware(['auth:sanctum', 'verified'])->get('/input', function () {
    return view('home');
})->name('input');
Route::middleware(['auth:sanctum', 'verified'])->resource('phone', App\Http\Controllers\NumberphoneController::class);
Route::middleware(['auth:sanctum', 'verified'])->get('/output', [App\Http\Controllers\NumberphoneController::class, 'index'])->name('output');
// Route::middleware(['auth:sanctum', 'verified'])->post('/update/{id}', [App\Http\Controllers\NumberphoneController::class, 'update'])->name('update');
Route::middleware(['auth:sanctum', 'verified'])->get('/edit/{id}', [App\Http\Controllers\NumberphoneController::class, 'edit'])->name('edit');
Route::middleware(['auth:sanctum', 'verified'])->get('/auto', [App\Http\Controllers\NumberphoneController::class, 'auto'])->name('auto');
Route::middleware(['auth:sanctum', 'verified'])->get('/getData', [App\Http\Controllers\NumberphoneController::class, 'output'])->name('getData');


Auth::routes();
Route::resource('phone', App\Http\Controllers\NumberphoneController::class);
// Route::get('/auto', [App\Http\Controllers\NumberphoneController::class, 'auto'])->name('auto');
// Route::get('/output', [App\Http\Controllers\NumberphoneController::class, 'index'])->name('output');
// Route::get('/getData', [App\Http\Controllers\NumberphoneController::class, 'output'])->name('getData');

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="row">
                    <div class="col-6">a</div>
                    <div class="col-6">a</div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    
    <div class="row justify-content-center">            
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit No Handphone</div>

                <div class="card-body">
                    <form action="{{route('phone.update',$data->id)}}" enctype="multipart/form-data" method="post">
                        @csrf @method('patch')
                        <input type="hidden" class="form-control" name="id" id="id" value="{{$data->id}}">
                        <div class="form-group">
                          <label for="exampleInputEmail1">No Handphone</label>
                          <input type="text" class="form-control" name="no_hp" id="no_hp" value="{{$data->no_hp}}">
                          {{-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> --}}
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlSelect1">Provider</label>
                            <select class="form-control" name="provider" id="provider">
                                <option disabled selected></option>
                                <option {{$data->provider=="xl" ? "selected":""}} value="xl">XL</option>
                                <option {{$data->provider=="telkom" ? "selected":""}} value="telkom">Telkom</option>
                                <option {{$data->provider=="tri" ? "selected":""}} value="tri">Tri</option>
                              {{-- <option>4</option> --}}
                              {{-- <option>5</option> --}}
                            </select>
                        </div><br>
                        <button type="submit"  class="btn btn-primary">Update</button>
                        <button type="button" id="batal" class="btn btn-primary">Batal</button>
                      </form>                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
    $('#batal').on('click', function (e) {
        window.location.replace("{{route('output')}}");
    });
</script>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    
    <div class="row justify-content-center">            
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Data No Handphone</div>

                <div class="card-body" >
                    <form id="form-data">
                        <div class="form-group">
                          <label for="exampleInputEmail1">No Handphone</label>
                          <input type="text" class="form-control" name="phone" id="phone">
                          
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlSelect1">Provider</label>
                            <select class="form-control" name="provider" id="provider">
                                <option disabled selected></option>
                                <option value="xl">XL</option>
                                <option value="telkom">Telkom</option>
                                <option value="tri">Tri</option>                              
                            </select>
                        </div><br>
                        <button type="button" id="simpan"  class="btn btn-primary">Simpan</button>
                        <button type="button" id="auto" class="btn btn-primary">auto</button>
                        <a type="button" href="{{route('output')}}" target="_blank" class="btn btn-primary">Output</a>
                      </form>                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
    $('#output').on('click', function (e) {
        window.location.replace("{{route('output')}}");
    });
    $('#simpan').on('click', function (e) {
        e.preventDefault();
        
        var phone = $('#phone').val();
        var provider = $('#provider').val();    
        $.ajax({
            url: "{{route('phone.store')}}",
            type: "POST",
            data: {
                _token: "{{ csrf_token() }}",
                no_hp: phone,
                provider: provider
            },
            success: function (s) {
                // alert(s.message);
                
                Swal.fire(
                'Remind!',
                'Create Phone Number successfully!',
                'success'
                )
                document.getElementById("form-data").reset();
            },
            error: function () {
                alert("Error", "Unable to bring up the dialog.", "error");
            }
        });
    });

    $('#auto').on('click', function (e) {
        e.preventDefault();
        $.ajax({
            url: "{{route('auto')}}",
            type: "get",
            success: function (s) {
                alert(s.message);       
                Swal.fire(
                'Remind!',
                'Auto Generate Phone Number successfully!',
                'success'
                )             
            },
            error: function () {
                alert("Error", "Unable to bring up the dialog.", "error");
            }
        });
    });
</script>

@endsection

resources/views/navigation-menu.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-jet-application-mark class="block h-9 w-auto" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-jet-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-jet-nav-link>
                </div>
            </div>

            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <!-- Teams Dropdown -->
                @if (Laravel\Jetstream\Jetstream::hasTeamFeatures())
                    <div class="ml-3 relative">
                        <x-jet-dropdown align="right" width="60">
                            <x-slot name="trigger">
                                <span class="inline-flex rounded-md">
                                    <button type="button" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:bg-gray-50 hover:text-gray-700 focus:outline-none focus:bg-gray-50 active:bg-gray-50 transition">
                                        {{ Auth::user()->currentTeam->name }}

                                        <svg class="ml-2 -mr-0.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                            <path fill-rule="evenodd" d="M10 3a1 1 0 01.707.293l3 3a1 1 0 01-1.414 1.414L10 5.414 7.707 7.707a1 1 0 01-1.414-1.414l3-3A1 1 0 0110 3zm-3.707 9.293a1 1 0 011.414 0L10 14.586l2.293-2.293a1 1 0 011.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clip-rule="evenodd" />
                                        </svg>
                                    </button>
                                </span>
                            </x-slot>

                            <x-slot name="content">
                                <div class="w-60">
                                    <!-- Team Management -->
                                    <div class="block px-4 py-2 text-xs text-gray-400">
                                        {{ __('Manage Team') }}
                                    </div>

                                    <!-- Team Settings -->
                                    <x-jet-dropdown-link href="{{ route('teams.show', Auth::user()->currentTeam->id) }}">
                                        {{ __('Team Settings') }}
                                    </x-jet-dropdown-link>

                                    @can('create', Laravel\Jetstream\Jetstream::newTeamModel())
                                        <x-jet-dropdown-link href="{{ route('teams.create') }}">
                                            {{ __('Create New Team') }}
                                        </x-jet-dropdown-link>
                                    @endcan

                                    <div class="border-t border-gray-100"></div>

                                    <!-- Team Switcher -->
                                    <div class="block px-4 py-2 text-xs text-gray-400">
                                        {{ __('Switch Teams') }}
                                    </div>

                                    @foreach (Auth::user()->allTeams() as $team)
                                        <x-jet-switchable-team :team="$team" />
                                    @endforeach
                                </div>
                            </x-slot>
                        </x-jet-dropdown>
                    </div>
                @endif

                <!-- Settings Dropdown -->
                <div class="ml-3 relative">
                    <x-jet-dropdown align="right" width="48">
                        <x-slot name="trigger">
                            @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
                                <button class="flex text-sm border-2 border-transparent rounded-full focus:outline-none focus:border-gray-300 transition">
                                    <img class="h-8 w-8 rounded-full object-cover" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                                </button>
                            @else
                                <span class="inline-flex rounded-md">
                                    <button type="button" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none transition">
                                        {{ Auth::user()->name }}

                                        <svg class="ml-2 -mr-0.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                            <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                        </svg>
                                    </button>
                                </span>
                            @endif
                        </x-slot>

                        <x-slot name="content">
                            <!-- Account Management -->
                            <div class="block px-4 py-2 text-xs text-gray-400">
                                {{ __('Manage Account') }}
                            </div>

                            <x-jet-dropdown-link href="{{ route('profile.show') }}">
                                {{ __('Profile') }}
                            </x-jet-dropdown-link>

                            @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                                <x-jet-dropdown-link href="{{ route('api-tokens.index') }}">
                                    {{ __('API Tokens') }}
                                </x-jet-dropdown-link>
                            @endif

                            <div class="border-t border-gray-100"></div>

                            <!-- Authentication -->
                            <form method="POST" action="{{ route('logout') }}">
                                @csrf

                                <x-jet-dropdown-link href="{{ route('logout') }}"
                                         onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                    {{ __('Log Out') }}
                                </x-jet-dropdown-link>
                            </form>
                        </x-slot>
                    </x-jet-dropdown>
                </div>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-jet-responsive-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-jet-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="flex items-center px-4">
                @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
                    <div class="shrink-0 mr-3">
                        <img class="h-10 w-10 rounded-full object-cover" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                    </div>
                @endif

                <div>
                    <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                    <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
                </div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Account Management -->
                <x-jet-responsive-nav-link href="{{ route('profile.show') }}" :active="request()->routeIs('profile.show')">
                    {{ __('Profile') }}
                </x-jet-responsive-nav-link>

                @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                    <x-jet-responsive-nav-link href="{{ route('api-tokens.index') }}" :active="request()->routeIs('api-tokens.index')">
                        {{ __('API Tokens') }}
                    </x-jet-responsive-nav-link>
                @endif

                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-jet-responsive-nav-link href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                    this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-jet-responsive-nav-link>
                </form>

                <!-- Team Management -->
                @if (Laravel\Jetstream\Jetstream::hasTeamFeatures())
                    <div class="border-t border-gray-200"></div>

                    <div class="block px-4 py-2 text-xs text-gray-400">
                        {{ __('Manage Team') }}
                    </div>

                    <!-- Team Settings -->
                    <x-jet-responsive-nav-link href="{{ route('teams.show', Auth::user()->currentTeam->id) }}" :active="request()->routeIs('teams.show')">
                        {{ __('Team Settings') }}
                    </x-jet-responsive-nav-link>

                    @can('create', Laravel\Jetstream\Jetstream::newTeamModel())
                        <x-jet-responsive-nav-link href="{{ route('teams.create') }}" :active="request()->routeIs('teams.create')">
                            {{ __('Create New Team') }}
                        </x-jet-responsive-nav-link>
                    @endcan

                    <div class="border-t border-gray-200"></div>

                    <!-- Team Switcher -->
                    <div class="block px-4 py-2 text-xs text-gray-400">
                        {{ __('Switch Teams') }}
                    </div>

                    @foreach (Auth::user()->allTeams() as $team)
                        <x-jet-switchable-team :team="$team" component="jet-responsive-nav-link" />
                    @endforeach
                @endif
            </div>
        </div>
    </div>
</nav>

resources/views/output.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    
    <div class="row justify-content-center">            
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Data No Handphone</div>

                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table" id="tableganjil">
                                <thead>
                                    <tr>
                                        <th>Ganjil</th>
                                        <th>Provider</th>
                                        <th>Action</th>                                                                      
                                    </tr>
                                </thead>
                                <tbody>

                                </tbody>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table class="table" id="tablegenap">
                                <thead>
                                    <tr>                                        
                                        <th>Genap</th>
                                        <th>Provider</th>  
                                        <th>Action</th>                              
                                    </tr>
                                </thead>
                                <tbody>

                                </tbody>
                            </table>
                        </div>
                    </div>
                    
                    
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="edit-modal" tabindex="-1" role="dialog" aria-labelledby="edit-modal-label" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="edit-modal-label">Edit Data</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body" id="attachment-body-content">
              <form id="edit-form" class="form-horizontal" method="POST" action="">
                <div class="card text-white bg-dark mb-0">
                  <div class="card-header">
                    <h2 class="m-0">Edit</h2>
                  </div>
                  <div class="card-body">
                    
                    <!-- name -->
                    <div class="form-group">
                      <label class="col-form-label" for="modal-input-name">No HP</label>
                      <input type="text" name="modal-input-nohp" class="form-control" id="modal-input-nohp" required autofocus>
                    </div>
                    <!-- /name -->
                    <!-- description -->
                    <div class="form-group">
                      <label class="col-form-label" for="modal-input-description">Provider</label>
                      <input type="text" name="modal-input-provider" class="form-control" id="modal-input-provider" required>
                    </div>
                    <!-- /description -->
                  </div>
                </div>
              </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-primary" data-dismiss="modal">Done</button>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
      
      
      
</div>
@endsection

@section('script')
{{-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> --}}
{{-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script> --}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{{-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> --}}
<script>
    
    function getData(){
        $.ajax({
            url: "{{route('getData')}}",
            type: "get",
            
            success: function (s) {
                // alert(s.message);
                // console.log(s)   
                setTable(s.ganjil,'ganjil');
                setTable(s.genap,'genap');

            },
            error: function () {
                alert("Error", "Unable to bring up the dialog.", "error");
            }
        });
    }

    function setTable(data,jenis){
        var trHTML = '';
        $.each(data, function (i, item) {
           
            trHTML += '<tr class="data-row">'+
                        '<td class="nohp">' + item.no_hp + '</td>'+
                        '<td class="provider">' + item.provider + '</td>'+
                        '<td>'+
                            '<button type="button" onClick="hapus('+item.id+')" class="btn btn-danger" >Hapus</button>'+
                            '<a type="button" type="button" href="/phone/'+item.id+'/edit" class="btn btn-primary" id="edit-item">Edit</a>'+
                        '</td></tr>';
        });
        if(jenis == 'ganjil'){
            $("#tableganjil > tbody").html(trHTML); 
        }
        if(jenis == 'genap'){
            $("#tablegenap > tbody").html(trHTML);
        }
    }

    function hapus(id){
        
        if(!confirm("Do you really want to do this?")) {
            return false;
        }
        var uri = "/phone/"+id;
        var token = $("meta[name='csrf-token']").attr("content");
        $.ajax(
        {
            url: uri,
            type: 'DELETE',
            data: {
                "id": id,
                _token: token,
            },
            success: function (){
                console.log("it Works");
                Swal.fire(
                'Remind!',
                'Phone Number deleted successfully!',
                'success'
                )
                getData();
            }
        });
        
    }

    $(document).ready(function() {

        getData();
        setInterval(function() {
            getData()}, 5000);
    });

</script>

@endsection

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>